spring.jmx.default-domain: demoboot
spring.application.name: demoboot
server:
   servlet.context-path: /demoboot
   tomcat.uri-encoding: UTF-8
spring:
   jackson:
      #日期格式化
      date-format: yyyy-MM-dd HH:mm:ss
      serialization:
         #格式化输出
         INDENT_OUTPUT: true
         #忽略无法转换的对象
         FAIL_ON_EMPTY_BEANS: false
         #设置空如何序列化
      defaultPropertyInclusion: NON_NULL
      deserialization:
         #允许对象忽略json中不存在的属性
         FAIL_ON_UNKNOWN_PROPERTIES: false
      parser:
         #允许出现特殊字符和转义符
         ALLOW_UNQUOTED_CONTROL_CHARS: true
         #允许出现单引号
         ALLOW_SINGLE_QUOTES: true
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DB_SERVER:localhost}:${DB_PORT:5432}/${DB_NAME:devbookdb}?ApplicationName=demoboot
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:130860}
      hikari:
         connection-test-query: SELECT 1
         maximum-pool-size: ${DB_POOL_SIZE:5}
         minimum-idle: ${HIKARICP_MINIMUM_IDLE:2}
         max-lifetime: ${HIKARICP_MAX_LIFETIME:900000}
         validation-timeout: ${HIKARICP_VALIDATION_TIMEOUT:5000}
         connection-timeout: ${HIKARICP_CONNECTION_TIMEOUT:30000}
         idle-timeout: ${HIKARICP_IDLE_TIMEOUT:600000}
         leakDetectionThreshold: 5000
   servlet:
      multipart:
         max-file-size: 10MB
   http:
      encoding:
         charset: UTF-8
         enabled: true
         force: true
mybatis:
   configuration.lazyLoadingEnabled: true
   mapper-locations: classpath:mapper/*.xml
   
   
   